version:
  name: velociraptor
  version: 0.7.0-2
  commit: 82f2cad
  build_time: "2023-09-10T15:23:01Z"
  install_time: 1694602109
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/6137985901
  compiler: go1.21.0
Client:
  server_urls:
  - https://localhost:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQXgIqwOiwy6pFCtcSA5fpsjANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMwOTEzMTA0ODUwWhcNMzMw
    OTEwMTA0ODUwWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDMFgtQj/ZmugjaBBulywedqzoHlBOvaWCB
    E5H1fImfttlimb4KHih7qtafpwrL0b+ZGxddJw+eNokUOw9UEjzKqopVQyrB8cS0
    ++kuCZ8+HLpfHE7iFUOwohnxn8C9b+oao0ySe9SVX2h3nGgXWC/+wYjH9nClQ4u4
    6IPWS3ThoP75+Yft0mRM2CKcRWOzbNxF2B3zw+DYT/7a/tApv0BMroc0phZIYM8K
    yVKbumVricxfFlE/trmIBc1PPP4UnHw9vPsQi1u2jiyvCRtclkI4rclkeKY2H/jN
    SKEgYRRtXvU8Hw8cZCZZmMuQsEhrviKnTUYq3Xj0UxARPtrZpwQrAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQY6jIMlZ4gHb9Vf9XH2DeGrztV
    xjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAcGTvdN74iQb4yP94eo3u9TtO33BCU86JCSPv5IFwtVhs
    PhUTBzhOoOmTC+8QdMVhGBvGQxOf50oZHNEffjbyMxwCXQdIGAM738UIORYIvNn0
    J82z3XsoUmhed2GLDBVrCd9mT5ziHowwKhcf5g+XNah8lD7JCJ0H5LxYkZvMHmod
    HU2i7A4INXPSCTwH/uoTNfVsAgO1nm9WaWUF0kXFeywmebGsg4dQ9LmG8fy9oruy
    A4YpoAmXh3R5GuXnVkThOLf3UIvWcJj99nSGOm9EspZxWJm7tEmLFDAq6HcPw24f
    yFg8dSG9BPmrorJhn8V8BTLHoHKaK/GV0sOdb9IDZQ==
    -----END CERTIFICATE-----
  nonce: BSgoq2dPq7I=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.0-2
    commit: 82f2cad
    build_time: "2023-09-10T15:23:01Z"
    install_time: 1694602109
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/6137985901
    compiler: go1.21.0
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
